site_name: FACINT - Projeto de Extensão 2025
extra_css:
  - css/extra.css
extra_javascript:
  - javascript/extra.js
theme:
  name: material
  logo: https://facint.edu.br/assets/images/logo/logo-1.png
  language: pt
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
  features:
    - navigation.expand
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
plugins:
  - search
markdown_extensions:
  - footnotes
nav:
  - Principal: 
    - Regulamento: index.md
  - Projeto prático:
    - Instruções: projeto/instrucoes.md
    - Exemplo de mockup: projeto/exemplo.md
  - Material escrito:
    - Instruções: material/instrucoes.md
    - Exemplo de documentação: material/exemplo.md
  - Vídeo gravado:
    - Instruções: video/instrucoes.md
    - Exemplo de vídeo: video/modelo.md